name: Deploy Python Script

on:
  push:
    branches:
      - main  # mainブランチにプッシュされたときに実行
      - feat/main-py-for-release-server

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # リポジトリをチェックアウト
    - name: Checkout repository
      uses: actions/checkout@v3

    # SSH接続の準備
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}

    # サーバーにPythonスクリプトをデプロイ
    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER_NAME }}@${{ secrets.DEPLOY_HOST_NAME }} << 'EOF'
        # デプロイ先ディレクトリへ移動
        cd ~/find-it/backend

        # 現在のプロセスを停止（プロセス管理ツールを使用）
        pkill -f main.py || true

        # 最新ファイルを取得
        git checkout main
        git pull
        ../.build

        # スクリプトを再起動
        nohup python3 main.py > output.log 2>&1 &
        EOF